### ISSUE TITLE
Google Earth: can it work after fixing libIGAttrs.so?

### ISSUE THREAD

**Issue by Botspot** [ptitSeb/box86#332] opened 2021-02-09 23:20 UTC
I've [downloaded](https://support.google.com/earth/answer/168344#zippy=%2Cdownload-a-google-earth-pro-direct-installer) the last available version of Google Earth that had 32-bit Linux support: v7.3.0.3832.

The deb had these dependencies:
```
lsb-core libfontconfig1 libx11-6 libxrender1 libxext6 libxtst6 libglu1-mesa libglib2.0-0 libsm6
```
I made sure all of the above dependencies were installed.

After extracting the deb and data.tar.xz, I located the shell script that launches Google Earth and tried running it:
```
pi@raspberrypi:~ $ /home/pi/Downloads/opt/google/earth/pro/googleearth
Box86 with Dynarec v0.1.9 258f7f9b built on Jan 11 2021 00:03:17
Warning, function my_vfscanf not found
Error: Global Symbol _ZN3Gap4Math20igMatrix44fMetaField10_MetaFieldE not found, cannot apply R_386_GLOB_DAT @0xeef1bb2c ((nil)) in libIGUtils.so
Error: Global Symbol _ZN3Gap4Math11igVec4fList5_MetaE not found, cannot apply R_386_GLOB_DAT @0xeef1bb70 ((nil)) in libIGUtils.so
Error: Global Symbol _ZN3Gap4Math11igVec3fList5_MetaE not found, cannot apply R_386_GLOB_DAT @0xeef1bfa8 ((nil)) in libIGUtils.so
Error: Symbol _ZN3Gap4Math16igVec3fMetaField20_instantiateFromPoolEPNS_4Core12igMemoryPoolE not found, cannot apply R_386_32 @0xeef1c4b0 ((nil)) in libIGUtils.so
Error: Symbol _ZN3Gap4Math16igVec3fMetaField20_instantiateFromPoolEPNS_4Core12igMemoryPoolE not found, cannot apply R_386_32 @0xeef1c5dc ((nil)) in libIGUtils.so
Error: Symbol _ZN3Gap4Math11igVec3fList11arkRegisterEv not found, cannot apply R_386_32 @0xeef1c4c8 ((nil)) in libIGUtils.so
Error: Symbol _ZN3Gap4Math16igVec4fMetaField20_instantiateFromPoolEPNS_4Core12igMemoryPoolE not found, cannot apply R_386_32 @0xeef1c4d8 ((nil)) in libIGUtils.so
Error: Symbol _ZN3Gap4Math16igVec4fMetaField20_instantiateFromPoolEPNS_4Core12igMemoryPoolE not found, cannot apply R_386_32 @0xeef1c4f0 ((nil)) in libIGUtils.so
Error: Symbol _ZN3Gap4Math16igVec4fMetaField20_instantiateFromPoolEPNS_4Core12igMemoryPoolE not found, cannot apply R_386_32 @0xeef1c5f4 ((nil)) in libIGUtils.so
Error: Symbol _ZN3Gap4Math11igVec4fList11arkRegisterEv not found, cannot apply R_386_32 @0xeef1c508 ((nil)) in libIGUtils.so
Error: Symbol _ZN3Gap4Math20igMatrix44fMetaField20_instantiateFromPoolEPNS_4Core12igMemoryPoolE not found, cannot apply R_386_32 @0xeef1c574 ((nil)) in libIGUtils.so
Error: Global Symbol _ZN3Gap3Gfx12igIndexArray5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b1d8 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx23igGfxShaderConstantList5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b2d8 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx20igTrackedElementList5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b3a0 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx12igScissorExt5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b3d8 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx35getIG_GFX_STENCIL_OPERATIONMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b3e4 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx20igPingPongIndexArray5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b46c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx26igTextureSamplerSourceList5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b470 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx31getIG_GFX_WINDING_ORDERMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b478 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx7igImage5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b4e8 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx18igBlendEquationExt5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b518 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx38getIG_GFX_TEXTURE_COORD_SOURCEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b534 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx30getIG_GFX_TEXTURE_WRAPMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b560 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx15igParticleArray5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b574 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx17igPrimLengthArray5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b5cc ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx32getIG_GFX_TEXTURE_SOURCEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b668 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx17igMultiTextureExt29getTEXTURE_STAGE_TYPEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b694 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx16igVertexDataList5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b6ac ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx30getIG_GFX_SHADING_MODEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b734 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx30getIG_GFX_TEXTURE_MODEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b740 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx16igPointSpriteExt35getIG_GFX_SPRITE_SIZE_SPACEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b7b0 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx22getIG_GFX_DRAWMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b7e0 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx21igPingPongVertexArray5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b7fc ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx20igOglMultiTextureExt31getTEXTURE_FUNCTION_OGLMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b81c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx13igVertexArray5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b84c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx15igVisualContext5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3b854 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx26getIG_GFX_FOG_MODEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b8d8 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx16igPointSpriteExt29getIG_GFX_SPRITE_TYPEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b8fc ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx29getIG_GFX_RENDER_MODEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b958 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx32getIG_GFX_TEXTURE_FILTERMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b974 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx38getIG_GFX_VERTEX_PIPELINE_MODEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3b9e0 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx35getIG_GFX_BLENDING_FUNCTIONMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3ba0c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx40getIG_GFX_RENDERDESTINATION_TYPEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3ba64 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx30getIG_GFX_SCISSOR_TYPEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3ba6c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx36getIG_GFX_MATERIAL_COMPONENTMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3bb5c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx17igMultiTextureExt27getTEXTURE_ARGUMENTMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3bb60 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx37getIG_GFX_PIXEL_PIPELINE_MODEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3bbc8 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx17igMultiTextureExt32getTEXTURE_FUNCTION_TYPEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3bbf8 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx21igGfxShaderDefineList5_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3bcf8 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx32getIG_GFX_CULL_FACE_MODEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3bd18 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx28getIG_GFX_LIGHT_TYPEMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3be1c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx34getIG_GFX_VERTEX_COMPONENTMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3be4c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx37getIG_GFX_DEPTH_TEST_FUNCTIONMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3be6c ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx34getIG_GFX_STENCIL_FUNCTIONMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3be88 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx32getIG_GFX_ALPHA_FUNCTIONMetaEnumEv not found, cannot apply R_386_GLOB_DAT @0xedd3bf54 ((nil)) in libIGAttrs.so
Error: Global Symbol _ZN3Gap3Gfx14igVertexArray25_MetaE not found, cannot apply R_386_GLOB_DAT @0xedd3bfe4 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3db38 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3df7c ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e020 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e2a8 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e344 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e468 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e4a0 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e690 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e964 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igVisualContext11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e9c4 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx13igVertexArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3db3c ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx13igVertexArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3de88 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx13igVertexArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e538 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx12igIndexArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3db40 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx12igIndexArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3de8c ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx12igIndexArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3df48 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx18igBlendEquationExt11arkRegisterEv not found, cannot apply R_386_32 @0xedd3dbb4 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx7igImage11arkRegisterEv not found, cannot apply R_386_32 @0xedd3dd2c ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx7igImage11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e5d0 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx7igImage11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e684 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx7igImage11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e6f0 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx7igImage11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e808 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx17igPrimLengthArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3debc ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx17igPrimLengthArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3df4c ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx14igVertexArray211arkRegisterEv not found, cannot apply R_386_32 @0xedd3df44 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx15igParticleArray11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e21c ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx26igTextureSamplerSourceList11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e2ac ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx23igGfxShaderConstantList11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e2b0 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx23igGfxShaderConstantList11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e958 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx21igGfxShaderDefineList11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e2b4 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx21igGfxShaderDefineList11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e960 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx20igTrackedElementList11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e954 ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx16igVertexDataList11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e95c ((nil)) in libIGAttrs.so
Error: Symbol _ZN3Gap3Gfx12igScissorExt11arkRegisterEv not found, cannot apply R_386_32 @0xedd3e9b4 ((nil)) in libIGAttrs.so
Error: PltReolver: Symbol _pthread_cleanup_push not found, cannot apply R_386_JMP_SLOT @0xf5c307d4 (0xf57b0386) in libQt5Core.so.5
8249|SIGSEGV @0x690403d4 (???(0x690403d4)) (x86pc=0xeef10274/libIGUtils.so:"libIGUtils.so/_ZN3Gap5Utils13igMatrixStack21arkRegisterInitializeEv + 72", esp=0xf6a50950), for accessing (nil) (code=1/prot=0), db=0x690f6880(0x69040310:0x69040538/0xeef10248:0xeef102ba/libIGUtils.so/_ZN3Gap5Utils13igMatrixStack21arkRegisterInitializeEv + 72:clean)
Google Earth has caught signal 11.



We apologize for the inconvenience, but Google Earth has crashed.
 This is a bug in the program, and should never happen under normal
 circumstances. A bug report and debugging data have been written
 to this text file:

    /home/pi/.googleearth/crashlogs/crashlog-6023174f.txt

Please include this file if you submit a bug report to Google.
```
To me, this looks like it would work if the libIGAttrs.so library was expanded with the required symbols.

**Comment by mobilegmYT** [comment] 2021-05-16 17:34
I tried running google earth with box64, it errors out also but seems more fixable

```
Box64 with Dynarec v0.0.8 f5c4deb built on Apr 14 2021 07:48:07
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 31 Env var
Looking for /opt/google/earth/pro/googleearth-bin
Using native(wrapped) libpthread.so.0
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libdl.so.2
Using emulated /opt/google/earth/pro/libgoogleearth_pro.so
Using emulated /opt/google/earth/pro/libQt5Gui.so.5
Using emulated /opt/google/earth/pro/libQt5Core.so.5
Using native(wrapped) libz.so.1
Using emulated /opt/google/earth/pro/libicui18n.so.54
Using emulated /opt/google/earth/pro/libicuuc.so.54
Using emulated /opt/google/earth/pro/libicudata.so.54
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /lib/x86_64-linux-gnu/libgthread-2.0.so.0
Using emulated /lib/x86_64-linux-gnu/libglib-2.0.so.0
Using emulated /lib/x86_64-linux-gnu/libpcre.so.3
Using native(wrapped) libGL.so.1
Using emulated /opt/google/earth/pro/libQt5Widgets.so.5
Using emulated /opt/google/earth/pro/libQt5Network.so.5
Using emulated /lib/x86_64-linux-gnu/libproxy.so.1
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libssl.so.1
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libX11.so.6
Using native(wrapped) libXrender.so.1
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libGLU.so.1
Using emulated /opt/google/earth/pro/libQt5DBus.so.5
Using native(wrapped) libdbus-1.so.3
Using emulated /opt/google/earth/pro/libQt5X11Extras.so.5
Using emulated /opt/google/earth/pro/libQt5Multimedia.so.5
Using emulated /opt/google/earth/pro/libQt5MultimediaWidgets.so.5
Using emulated /opt/google/earth/pro/libQt5OpenGL.so.5
Using emulated /opt/google/earth/pro/libQt5Positioning.so.5
Using emulated /opt/google/earth/pro/libQt5PrintSupport.so.5
Using emulated /opt/google/earth/pro/libQt5Qml.so.5
Using emulated /opt/google/earth/pro/libQt5Quick.so.5
Using emulated /opt/google/earth/pro/libQt5Script.so.5
Using emulated /opt/google/earth/pro/libQt5ScriptTools.so.5
Using emulated /opt/google/earth/pro/libQt5Sensors.so.5
Using emulated /opt/google/earth/pro/libQt5Sql.so.5
Error: Symbol posix_fallocate64 not found, cannot apply R_X86_64_64 @0x7f84afea50 ((nil)) in /opt/google/earth/pro/libQt5Sql.so.5
Using emulated /opt/google/earth/pro/libQt5Svg.so.5
Using emulated /opt/google/earth/pro/libQt5WebChannel.so.5
Using emulated /opt/google/earth/pro/libQt5WebKit.so.5
Using native(wrapped) libXcomposite.so.1
Using emulated /lib/x86_64-linux-gnu/libxml2.so.2
Using emulated /lib/x86_64-linux-gnu/libicuuc.so.67
Using emulated /lib/x86_64-linux-gnu/libicudata.so.67
Using native(wrapped) liblzma.so.5
Using emulated /lib/x86_64-linux-gnu/libgio-2.0.so.0
Using emulated /lib/x86_64-linux-gnu/libgobject-2.0.so.0
Using emulated /lib/x86_64-linux-gnu/libffi.so.7
Using emulated /lib/x86_64-linux-gnu/libgmodule-2.0.so.0
Using emulated /lib/x86_64-linux-gnu/libmount.so.1
Using emulated /lib/x86_64-linux-gnu/libblkid.so.1
Using emulated /lib/x86_64-linux-gnu/libselinux.so.1
Using emulated /lib/x86_64-linux-gnu/libpcre2-8.so.0
Using native(wrapped) libresolv.so.2
Using emulated /lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
Using emulated /lib/x86_64-linux-gnu/libunwind.so.8
Using emulated /lib/x86_64-linux-gnu/libdw.so.1
Using emulated /lib/x86_64-linux-gnu/libelf.so.1
Using native(wrapped) libbz2.so.1
Using emulated /lib/x86_64-linux-gnu/libgstapp-1.0.so.0
Using emulated /lib/x86_64-linux-gnu/libgstbase-1.0.so.0
Using emulated /lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0
Using emulated /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
Using emulated /lib/x86_64-linux-gnu/liborc-0.4.so.0
Using emulated /lib/x86_64-linux-gnu/libgstaudio-1.0.so.0
Using emulated /lib/x86_64-linux-gnu/libgsttag-1.0.so.0
Error loading needed lib: "libsqlite3.so.0"
Error loading needed lib: "libQt5WebKit.so.5"
Error loading needed lib: "libgoogleearth_pro.so"
Error: loading needed libs in elf /opt/google/earth/pro/googleearth-bin
```

**Comment by ptitSeb** [comment] 2022-05-10 15:18
So what, adding the `posix_fallocate64` wrapped function to box64? That's a box86 ticket (the orginial ticket seems quite outdated)

**Comment by ptitSeb** [comment] 2022-10-11 15:41
I close this ticket. If the issue is still there on box86, feel free to re-open it. If some wrapping is needed on box64, please open a new ticket there.

**Closed by ptitSeb** 2022-10-11 15:41 UTC
