### ISSUE TITLE
Need help with aarch64.. kernel32.dll error 

### ISSUE THREAD

**Issue by Saikatsaha1996** [ptitSeb/box86#658] opened 2022-07-19 04:58 UTC
Help wanted please help..

![Screenshot_2022-07-19-06-51-08-532_x org server](https://user-images.githubusercontent.com/72664192/179668182-7ca2eaaf-a209-4246-aa54-1034cfeff43e.jpg)

**Comment by WheezyE** [comment] 2022-07-19 05:14
I believe this is in reference to this setup on Android Termux?
https://github.com/lowspecman420/AnBox86/issues/17#issuecomment-1188501677

I haven’t had time to set my Pi’s back up and test box86 stuff but I’m planning to check it out some time hopefully soon

**Comment by Saikatsaha1996** [comment] 2022-07-19 05:15
> I believe this is in reference to this setup on Android Termux? [lowspecman420/AnBox86#17 (comment)](https://github.com/lowspecman420/AnBox86/issues/17#issuecomment-1188501677)
> 
> I haven’t had time to set my Pi’s back up and test box86 stuff but I’m planning to check it out some time hopefully soon

No andbox not working... I tried.... Box86 not found..

**Comment by Saikatsaha1996** [comment] 2022-07-19 05:17
> I believe this is in reference to this setup on Android Termux? [lowspecman420/AnBox86#17 (comment)](https://github.com/lowspecman420/AnBox86/issues/17#issuecomment-1188501677)
> 
> I haven’t had time to set my Pi’s back up and test box86 stuff but I’m planning to check it out some time hopefully soon
See my error list ..

**Comment by WheezyE** [comment] 2022-07-19 05:25
It looks like you’re running the XServer XSDL Android app (based on the screen overlay icons in top-left). Which hardware are you running box86 on? Android? Pi? RockChip?

**Comment by Saikatsaha1996** [comment] 2022-07-19 05:26
> It looks like you’re running the XServer XSDL Android app (based on the screen overlay icons in top-left). Which hardware are you running box86 on? Android? Pi? RockChip?

Android 12

**Comment by ptitSeb** [comment] 2022-07-19 06:11
You are using old version of box86, please update (490cabcb is from 17th of april, but build date in 18th of hanuary?)

**Comment by ptitSeb** [comment] 2022-07-19 06:11
is this using the VM feature of android12?

**Comment by Saikatsaha1996** [comment] 2022-07-19 06:13
> is this using the VM feature of android12?

No no.. 

Proot environment aarch64 android

**Comment by Saikatsaha1996** [comment] 2022-07-19 15:33
> is this using the VM feature of android12?

@ptitSeb can you help me?..

I just completely build box86 && box64 and installed..
Wine32 and wine64 also downloaded... But not installed..


Can you guide me.. how can I install wine64 && wine32 together?..

![Screenshot_2022-07-19-21-03-27-107_com termux](https://user-images.githubusercontent.com/72664192/179790326-aaf9a63f-3ec6-4343-b13c-f5c04dbc352e.jpg)

**Comment by ptitSeb** [comment] 2022-07-19 15:53
termux doesn't allow binfmt integration IIRC. So box86 and box64 will not be called automatically. You need to use box64 or box86 directly. For bash file, maybe use the `bash` copy that is in box86 and box64?

**Comment by Saikatsaha1996** [comment] 2022-07-19 15:58
> termux doesn't allow binfmt integration IIRC. So box86 and box64 will not be called automatically. You need to use box64 or box86 directly. For bash file, maybe use the `bash` copy that is in box86 and box64?

No no .. box86 && box64 is oky .. but need to install wine.. how can I install wine ? ..
Wine already downloaded.. but not installed..

**Comment by ptitSeb** [comment] 2022-07-19 16:03
find a tgz of wine and just extract the files.
Like from there: https://github.com/Kron4ek/Wine-Builds/releases

but use older version, like 7.3 maximum. 5.3 to 7.3 should works fine, including stagging.

**Comment by Saikatsaha1996** [comment] 2022-07-19 16:04
> find a tgz of wine and just extract the files. Like from there: https://github.com/Kron4ek/Wine-Builds/releases
> 
> but use older version, like 7.3 maximum. 5.3 to 7.3 should works fine, including stagging.

Ohhh .. i am useing wine 7.13

**Comment by Saikatsaha1996** [comment] 2022-07-19 16:17
> @ptitSeb don't know why wine32 bit not working..
> 
> Anything missing? Wine-devel 7.13
> 
> ```
> root@localhost:~# wine/bin box86 wine --version         -bash: wine/bin: Is a directory
> root@localhost:~# box86 wine/bin/wine --version
> Box86 with Dynarec v0.2.7 fa8355ec built on Jul 19 2022 15:19:03
> Error: Symbol __gmtime64 not found, cannot apply R_386_JMP_SLOT 0xf0f82010 (0x6056) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __localtime64 not found, cannot apply R_386_JMP_SLOT 0xf0f82020 (0x6096) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __stat64_time64 not found, cannot apply R_386_JMP_SLOT 0xf0f82034 (0x60e6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __fstatat64_time64 not found, cannot apply R_386_JMP_SLOT 0xf0f82044 (0x6126) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __recvmsg64 not found, cannot apply R_386_JMP_SLOT 0xf0f8206c (0x61c6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __futimens64 not found, cannot apply R_386_JMP_SLOT 0xf0f82088 (0x6236) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __getsockopt64 not found, cannot apply R_386_JMP_SLOT 0xf0f820ac (0x62c6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __sendmsg64 not found, cannot apply R_386_JMP_SLOT 0xf0f820c8 (0x6336) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __fstat64_time64 not found, cannot apply R_386_JMP_SLOT 0xf0f820e4 (0x63a6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __clock_getres64 not found, cannot apply R_386_JMP_SLOT 0xf0f820e8 (0x63b6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __setsockopt64 not found, cannot apply R_386_JMP_SLOT 0xf0f82134 (0x64e6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __select64 not found, cannot apply R_386_JMP_SLOT 0xf0f8213c (0x6506) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __fcntl_time64 not found, cannot apply R_386_JMP_SLOT 0xf0f82144 (0x6526) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __lstat64_time64 not found, cannot apply R_386_JMP_SLOT 0xf0f821f4 (0x67e6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __ctime64 not found, cannot apply R_386_JMP_SLOT 0xf0f82204 (0x6826) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __gettimeofday64 not found, cannot apply R_386_JMP_SLOT 0xf0f82238 (0x68f6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __ioctl_time64 not found, cannot apply R_386_JMP_SLOT 0xf0f82268 (0x69b6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __mktime64 not found, cannot apply R_386_JMP_SLOT 0xf0f82288 (0x6a36) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> Error: Symbol __time64 not found, cannot apply R_386_JMP_SLOT 0xf0f822b8 (0x6af6) in /root/wine/bin/../lib/wine/i386-unix/ntdll.so
> wine-7.13
> root@localhost:~# box64 wine/bin/wine64 --version
> Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
> Box64 with Dynarec v0.1.9 0931f95 built on Jul 19 2022 15:11:13
> BOX64: Wine64 detected, WINEPRELOADRESERVE=""
> Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
> Using default BOX64_PATH: ./:bin/
> Counted 31 Env var
> Looking for wine/bin/wine64
> argv[1]="--version"
> Rename process to "wine64"
> Using native(wrapped) libdl.so.2
> Using native(wrapped) libc.so.6
> Using native(wrapped) ld-linux-x86-64.so.2
> Using native(wrapped) libpthread.so.0
> Using native(wrapped) librt.so.1
> Using emulated /root/wine/bin/../lib64/wine/x86_64-unix/ntdll.so
> Using native(wrapped) libunwind.so.8
> wine-7.13
> root@localhost:~#
> ```
> 
> ![Screenshot_2022-07-19-21-30-34-968_com termux](https://user-images.githubusercontent.com/72664192/179796642-ccb6959b-6e63-42b6-8a9b-3b6689403f4e.jpg)

@ptitSeb understand.. and solved..

I over ride all 32 bit and 64 bit lib folders.. that's why all missmatch.. 🥵

**Comment by ptitSeb** [comment] 2022-07-19 16:45
install what?

**Comment by Saikatsaha1996** [comment] 2022-07-19 17:00
> you add a line like `export PATH=/home/me/wine/bin:$PATH`?

Okay thank you understand ❤️

**Comment by Saikatsaha1996** [comment] 2022-07-19 17:48
> you add a line like `export PATH=/home/me/wine/bin:$PATH`?

`Faild to open rpcss service `

![Screenshot_2022-07-19-23-16-43-343_x org server](https://user-images.githubusercontent.com/72664192/179816073-880768d0-28cf-4a53-a3fe-288100c7b69b.jpg)
![Screenshot_2022-07-19-23-12-33-289_x org server](https://user-images.githubusercontent.com/72664192/179816089-f3e6c555-03a9-406a-915f-eaa2cb4ed311.jpg)

**Comment by ptitSeb** [comment] 2022-10-12 20:06
Is the issue still present? This ticket is bit long and I'm not sure what is left unresolved.

**Comment by chungyuhoi** [comment] 2022-10-18 23:53
You can download "wine" throung URL:https://www.playonlinux.com/wine/binaries/phoenicis/ ,with termux，I suggest you select upstream-linux-x86,whichmean Architecture i386. 
1 prepare: dpkg --add-architecture armhf && sudo apt install zenity:armhf libegl-mesa0:armhf libgl1-mesa-dri:armhf libglapi-mesa:armhf libglx-mesa0:armhf libasound*:armhf libstdc++6:armhf gcc-arm-linux-gnueabihf sl:armhf -y
2 extract wine: tar zxvf wine*.tar.gz -C /usr
3 run: box86 wine taskmgr

**Comment by chungyuhoi** [comment] 2022-10-19 00:14
I forgot after dpkg --add-architecture i386, Do "sudo apt update"

**Comment by Saikatsaha1996** [comment] 2023-01-23 02:53
> find a tgz of wine and just extract the files. Like from there: https://github.com/Kron4ek/Wine-Builds/releases
> 
> but use older version, like 7.3 maximum. 5.3 to 7.3 should works fine, including stagging.

Still i can't run DirectX.exe, any game or etc..

Any solution please?
I am facing problem with alsa sound..

**Comment by Saikatsaha1996** [comment] 2023-01-24 13:27
> You are using old version of box86, please update ([490cabc](https://github.com/ptitSeb/box86/commit/490cabcbe3ff8c0458e764af9b282e68a393f2be) is from 17th of april, but build date in 18th of hanuary?)
@ptitSeb 
It is serious issue for all proot users..

Can't even install this game..
And some games installed but can't even launch same error..
Can it possible any solution?
Actually i am on proot..
In other emulator same game working but can't use box86 or box64

I hope it can be solve ..

https://user-images.githubusercontent.com/72664192/214306612-a9b73ab1-4bce-445e-9e3f-ac3e9c057925.mp4

**Comment by myself600** [comment] 2023-01-24 23:39
What version of box86 and Wine are you running?

**Comment by Saikatsaha1996** [comment] 2023-01-25 04:46
> What version of box86, Wine and Mesa are you running? Are they up-to-date?

```
root@localhost:~# box86 --version
Box86 with Dynarec v0.2.9 8e88ca69 built on Jan 24 2023 23:02:28
```

**Comment by myself600** [comment] 2023-01-25 07:48
Mesa? Snapdragon 865 uses Adreno 650 (https://github.com/ptitSeb/box86/issues/658#issuecomment-1188613132), which is supported by Freedreno, not Panfrost so something doesn't add up. What is the ouput of `glxinfo|grep "OpenGL renderer string"`?

**Comment by Saikatsaha1996** [comment] 2023-01-25 07:51
> Mesa? Snapdragon 865 uses Adreno 650 ([#658 (comment)](https://github.com/ptitSeb/box86/issues/658#issuecomment-1188613132)), which is supported by Freedreno, not Panfrost so something doesn't add up. What is the ouput of `glxinfo|grep "OpenGL renderer string"`?

Actually i am on Mali..

**Comment by myself600** [comment] 2023-01-25 07:53
What device? What Mesa version? What distro?

**Comment by Saikatsaha1996** [comment] 2023-01-25 07:54
> What device? What Mesa version? What distro?

![Screenshot_2023-01-25-13-23-39-821_com gaurav avnc](https://user-images.githubusercontent.com/72664192/214508824-9279aa32-00ee-4cfc-bcf3-ac8b3d7fecc3.jpg)

Ubuntu 22.04
Proot linux Android..
Mesa 23

**Comment by myself600** [comment] 2023-01-25 07:59
Ok, try downgrading Mesa to 22.2 as see what happens. Only OpenGL is working for me with the latest Mesa (also Panfrost).

**Comment by Saikatsaha1996** [comment] 2023-01-25 08:03
> Ok, try downgrading Mesa to 22.2 as see what happens. Only OpenGL is working for me with the latest Mesa (also Panfrost).

I don't have support another mesa..
I panfrost original driver only work with rooted device..
But i am not rooted.. and my OpenGL GPU in wine working fine.. only problem with sound..


`box86 wine dxdiag`
Output
```
Box86 with Dynarec v0.2.9 8e88ca69 built on Jan 24 2023 23:02:28
00c8:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
00c8:err:winediag:wined3d_dll_init Using the OpenGL renderer.
00c8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00c8:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x30
00c8:fixme:wbemprox:enum_class_object_Next timeout not supported
00c8:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Panfrost". Returning HW_VENDOR_NVIDIA.
00c8:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Panfrost". Returning HW_VENDOR_NVIDIA.
00c8:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
00c8:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
00c8:fixme:dxdiag:wWinMain Information dialog is not implemented
```
Same output with `llvmpipe` driver.. 
This is not my GPU driver issue..

**Comment by myself600** [comment] 2023-01-25 08:05
So the issue is with sound and not DirectX?

**Comment by Saikatsaha1996** [comment] 2023-01-25 08:07
> So the issue is with sound and not DirectX?

Wine sound test also working..
But only DirectX sound not working..

**Comment by myself600** [comment] 2023-01-25 08:20
Hmm.. haven't had this problem myself, so I'm not sure. [This forum post](https://bbs.archlinux.org/viewtopic.php?pid=1830323#p1830323) suggests running `sudo modprobe snd_seq` ...

**Comment by Saikatsaha1996** [comment] 2023-01-25 08:21
> Hmm.. haven't had this problem myself, so I'm not sure. [This forum post](https://bbs.archlinux.org/viewtopic.php?pid=1830323#p1830323) suggests running `sudo modprobe snd_seq` ...

Yes but i am not rooted & i am on Android it will won't work..

**Comment by myself600** [comment] 2023-01-25 08:25
Well.. I would suggest to root the device then

**Comment by Saikatsaha1996** [comment] 2023-01-25 08:33
> Well.. I would suggest to root the device then

😀
Actually i am waiting for dev .
Because i believe Dev can help..
Because in fex-emulator i haven't any  error..

**Comment by ThieuMinh26** [comment] 2023-01-25 08:40
> > So the issue is with sound and not DirectX?
> 
> Wine sound test also working.. But only DirectX sound not working..
> 
> Inside fex-emulator all working.. but it's horrible very slow..

Fex is fast enough if you have strong 64bit only cpu  . You must use `FEXConfig` to tweak it

**Comment by Saikatsaha1996** [comment] 2023-01-25 08:52
> > > So the issue is with sound and not DirectX?
> > 
> > 
> > Wine sound test also working.. But only DirectX sound not working..
> > Inside fex-emulator all working.. but it's horrible very slow..
> 
> Fex is fast enough if you have strong 64bit only cpu . You must use `FEXConfig` to tweak it

I have Mediatek Dimensity 8100 CPU..
I already reported in Fex-emulator Discord.. about my problem.. you can check problem name With @HappY in fex discord.. winecfg opening time was 1.5 hours..

**Comment by ptitSeb** [comment] 2023-01-25 11:38
This ticket is quite confusing.

Can you sum-up what the problem is. Is the title of the ticket still relevant or does it evolved to something else?

**Comment by Saikatsaha1996** [comment] 2023-01-25 11:48
> This ticket is quite confusing.
> 
> Can you sum-up what the problem is. Is the title of the ticket still relevant or does it evolved to something else?

Kernel 32 bit issue solved with.. your solution..

https://github.com/ptitSeb/box86/issues/658#issuecomment-1189246521

But problem.. not a single DirectX game working.. because DirectX sound not working..

I am bit confused.. wine test sound works fine..
But when i am trying to run `box86 wine dxdiag`
I am getting error..
```
Box86 with Dynarec v0.2.9 8e88ca69 built on Jan 24 2023 23:02:28
00c8:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
00c8:err:winediag:wined3d_dll_init Using the OpenGL renderer.
00c8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00c8:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x30
00c8:fixme:wbemprox:enum_class_object_Next timeout not supported
00c8:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Panfrost". Returning HW_VENDOR_NVIDIA.
00c8:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Panfrost". Returning HW_VENDOR_NVIDIA.
00c8:fixme:ddraw:ddraw7_Initialize Ignoring guid {aeb2cdd4-6e41-43ea-941c-8361cc760781}.
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
00c8:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
00c8:fixme:dxdiag:wWinMain Information dialog is not implemented
```
In Android not supported `alsa` sound works via `pulse audio` server `127.0.0.1`

Trying to install ETS2 but crashed..
https://github.com/ptitSeb/box86/issues/658#issuecomment-1401949538

I believe all crashed related with DirectX sound.. 
I hope you understand..
Same problem with
`box86 & box64`

**Comment by ThieuMinh26** [comment] 2023-01-25 12:31
> not a single DirectX game working.. because DirectX sound not working..

You are wrong, the game works directx. This is the proof :
https://youtu.be/RIEfNj6FvVA

**Comment by Saikatsaha1996** [comment] 2023-01-25 12:34
> > not a single DirectX game working.. because DirectX sound not working..
> 
> You are wrong, the game works with directx. This is the proof : https://youtu.be/RIEfNj6FvVA

Really i am now fully confused 🤔
In my case games crashed..
Directx not even opening

**Comment by ThieuMinh26** [comment] 2023-01-25 12:39
> > > not a single DirectX game working.. because DirectX sound not working..
> > 
> > 
> > You are wrong, the game works with directx. This is the proof : https://youtu.be/RIEfNj6FvVA
> 
> Really i am now fully confused thinking In my case games crashed.. Directx not even opening

You have to accept it , this is not linux vm but proot , its android problem

**Comment by Saikatsaha1996** [comment] 2023-01-25 12:43
> > > > not a single DirectX game working.. because DirectX sound not working..
> > > 
> > > 
> > > You are wrong, the game works with directx. This is the proof : https://youtu.be/RIEfNj6FvVA
> > 
> > 
> > Really i am now fully confused thinking In my case games crashed.. Directx not even opening
> 
> You have to accept it , this is not linux vm but proot , its android problem

Can you share your `zink` script?

**Comment by ThieuMinh26** [comment] 2023-01-25 12:44
> Can you share your `zink` script?

alias zink='GALLIUM_DRIVER=virpipe'

**Comment by Saikatsaha1996** [comment] 2023-01-25 12:47
> > Can you share your `zink` script?
> 
> alias zink='GALLIUM_DRIVER=virpipe'

But i am on Panfrost..

So in my case it should be

`panfrost='GALLIUM_DRIVER=panfrost'` ?

**Comment by ThieuMinh26** [comment] 2023-01-25 12:50
> So in my case it should be
> 
> `panfrost='GALLIUM_DRIVER=panfrost'` ?

I dont know , i dont have any compatible mali gpu

**Comment by Saikatsaha1996** [comment] 2023-01-25 12:54
> > So in my case it should be
> > `panfrost='GALLIUM_DRIVER=panfrost'` ?
> 
> I dont know , i dont have any compatible mali gpu for panfrost

I don't have vulkan driver.. it can be reason?

![IMG_20230125_182352](https://user-images.githubusercontent.com/72664192/214568487-650f1524-5710-4807-8977-96a2a3b55f3a.jpg)

**Comment by ThieuMinh26** [comment] 2023-01-25 12:57
> ![IMG_20230125_182352](https://user-images.githubusercontent.com/72664192/214568487-650f1524-5710-4807-8977-96a2a3b55f3a.jpg)

wow this is fast , llvmpipe or virpipe or panfrost ?

**Comment by ptitSeb** [comment] 2023-01-25 12:58
I'm closing this ticket, as the initial issue has been fixed.

For your other issue, I suggest you create a new Discussion (not a ticket), to discuss what could be the best configuration to run box86/box64 in your proot environnement. Solution using PANFROST will be different than solution with Freedreno (that can use native vulkan and zink).

(for sound issue, check if you are using Alsa or PulseAudio, and check that you have  both 32bits and 64bits version of the libs. also check for libFAudio, as it is now supported in both box86 & box64)

**Closed by ptitSeb** 2023-01-25 12:58 UTC
Labels: App not running, Wine, Phone, 64bits

**Comment by Saikatsaha1996** [comment] 2023-01-25 13:07
> I'm closing this ticket, as the initial issue has been fixed.
> 
> For your other issue, I suggest you create a new Discussion (not a ticket), to discuss what could be the best configuration to run box86/box64 in your proot environnement. Solution using PANFROST will be different than solution with Freedreno (that can use native vulkan and zink).
> 
> (for sound issue, check if you are using Alsa or PulseAudio, and check that you have both 32bits and 64bits version of the libs. also check for libFAudio, as it is now supported in both box86 & box64)

Okay so i don't have vulkan support that's why getting crashed?
And panfrost driver not supported?

**Comment by ThieuMinh26** [comment] 2023-01-25 13:15
> It is panfrost

Wow íts possible in proot ?

**Comment by Saikatsaha1996** [comment] 2023-01-25 13:16
> > It is panfrost
> 
> Wow íts possible in proot ?

Now supported for others GPU..
Only intial support `Mali G-610`
And under testing `Mali G-52`

**Comment by Saikatsaha1996** [comment] 2023-01-25 13:37
> I'm closing this ticket, as the initial issue has been fixed.
> 
> For your other issue, I suggest you create a new Discussion (not a ticket), to discuss what could be the best configuration to run box86/box64 in your proot environnement. Solution using PANFROST will be different than solution with Freedreno (that can use native vulkan and zink).
> 
> (for sound issue, check if you are using Alsa or PulseAudio, and check that you have both 32bits and 64bits version of the libs. also check for libFAudio, as it is now supported in both box86 & box64)

Can you please tell me is my GPU not supported?
I don't have vulkan support.. for this reason not working ?
If yes, then i should leave..

**Comment by Saikatsaha1996** [comment] 2023-01-25 13:42
> > Can you please tell me is my GPU not supported? I don't have vulkan support.. for this reason not working ? If yes, then i should leave..
> 
> Its more like proot problem . As wine transalate DirectX 9/10/11 -> OpenGL

🥺 And yes my GPU driver not supported `sys call`
That's why i LOGIN with `--no-sysvipc`

**Comment by ptitSeb** [comment] 2023-01-25 13:52
> > I'm closing this ticket, as the initial issue has been fixed.
> > For your other issue, I suggest you create a new Discussion (not a ticket), to discuss what could be the best configuration to run box86/box64 in your proot environnement. Solution using PANFROST will be different than solution with Freedreno (that can use native vulkan and zink).
> > (for sound issue, check if you are using Alsa or PulseAudio, and check that you have both 32bits and 64bits version of the libs. also check for libFAudio, as it is now supported in both box86 & box64)
> 
> Can you please tell me is my GPU not supported? I don't have vulkan support.. for this reason not working ? If yes, then i should leave..

I don't sk you to lave: I suggest you open a Discussion ticket, as it might interest other user. But with the title of that ticket, now one will found it to discuss about using panfrost inside a termux proot

**Comment by Saikatsaha1996** [comment] 2023-01-25 17:01
> > > I'm closing this ticket, as the initial issue has been fixed.
> > > For your other issue, I suggest you create a new Discussion (not a ticket), to discuss what could be the best configuration to run box86/box64 in your proot environnement. Solution using PANFROST will be different than solution with Freedreno (that can use native vulkan and zink).
> > > (for sound issue, check if you are using Alsa or PulseAudio, and check that you have both 32bits and 64bits version of the libs. also check for libFAudio, as it is now supported in both box86 & box64)
> > 
> > 
> > Can you please tell me is my GPU not supported? I don't have vulkan support.. for this reason not working ? If yes, then i should leave..
> 
> I don't ask you to lave: I suggest you open a Discussion ticket, as it might interest other user. But with the title of that ticket, now one will found it to discuss about using panfrost inside a termux proot

I am sharing some `important` information..
Inside `fex-emulator`
Same `directx` not opening..
Same `error` received...
But game not crashed.. 
![Screenshot_2023-01-25-22-15-08-547_com gaurav avnc](https://user-images.githubusercontent.com/72664192/214629673-b9901c0f-feab-490d-a417-47b218a99666.jpg)
![Screenshot_2023-01-25-22-06-03-738_com gaurav avnc](https://user-images.githubusercontent.com/72664192/214629701-a315664d-dcd7-4354-bcfe-e38ea6e24b9b.jpg)

**Comment by ptitSeb** [comment] 2023-01-25 17:04
I don't have Euro Truck Simulator 2 in my collections. I cannot test myself. Is the game a 32bits or 64bits apps?

**Comment by Saikatsaha1996** [comment] 2023-01-25 17:08
> I don't have Euro Truck Simulator 2 in my collections. I cannot test myself. Is the game a 32bits or 64bits apps?

`32 bit` collected from exagear
Same error received from box64 also..
Openrail installed successfully..
But not working.. was crashed.. and same error received like which i received from ETS2

**Comment by Saikatsaha1996** [comment] 2023-01-25 17:11
> I don't have Euro Truck Simulator 2 in my collections. I cannot test myself. Is the game a 32bits or 64bits apps?

You can test with Openrail 30 to 40 mb application without data..
U can install.. and try to start the `exe`

**Comment by Saikatsaha1996** [comment] 2023-01-29 07:15
> I don't have Euro Truck Simulator 2 in my collections. I cannot test myself. Is the game a 32bits or 64bits apps?
@ptitSeb 

## Euro truck simulator 2 

 inside fex-emulator Euro truck simulator working
![Screenshot_2023-01-28-16-28-53-667_com termux x11](https://user-images.githubusercontent.com/72664192/215310805-0769b77d-df49-45ac-8a34-bef7deafecb6.jpg)
![Screenshot_2023-01-28-16-14-14-248_com termux x11](https://user-images.githubusercontent.com/72664192/215310811-d21c7a7d-4442-425f-b0ad-4dd0b9ec7a07.jpg)
## openrail 
Openrail opening inside fex-emulator but crashed fully..
I think is proot issue..
![Screenshot_2023-01-27-04-12-39-476_com gaurav avnc](https://user-images.githubusercontent.com/72664192/215310996-e22b2e6d-3598-46ac-80da-01b238fea9b9.jpg)

But inside box86 & box64 
Euro truck simulator 2 not installing
Openrail not opening..
So i guess box64 & box86 has also some issue..
If you want to fix i can help you with test report..

DirectX issue is common inside proot..
Only DirectX working fine inside exagear
Openrail working inside exagear
Euro truck simulator 2 working inside exagear

**Comment by ptitSeb** [comment] 2023-01-30 13:16
I tested OpenRail and Euro Truck Simulator 2 (demo version) on my Phytium ARM mini PC. It's full ARM computer, with a Radeon RX550 graphic card, running Debian (testing).
I used Wine 8.0 64bits, with dxvk 2.0

I could launch OpenRail
![Screenshot at 2023-01-29 11-16-10](https://user-images.githubusercontent.com/3250792/215486995-d99c1af9-012a-4963-baec-4c846d656f95.png)
But the game itself didn't launched, it failed to open graphics. It's probably due to the need to install xna31, but I couldn't install dotnet2 that is a prerequisite. That's probably an box86 issue there.

Euro Truck also installed without issue. The 64bits version launch and works, using dxvk
![Screenshot at 2023-01-29 20-28-03](https://user-images.githubusercontent.com/3250792/215487465-1a82c2e0-e0e8-4359-815f-caf5acff0976.png)

But the 32bits version doesn't, the dxvk context fails at creation.

I think the issue you have on your side is because PROOT doesn't handle Signal in a perfect way, and box86/box64 absolutly needs good signal handling, espcialy with program that use C# (or other languages using a JIT).

**Comment by Saikatsaha1996** [comment] 2023-01-30 13:23
> I tested OpenRail and Euro Truck Simulator 2 (demo version) on my Phytium ARM mini PC. It's full ARM computer, with a Radeon RX550 graphic card, running Debian (testing). I used Wine 8.0 64bits, with dxvk 2.0
> 
> I could launch OpenRail ![Screenshot at 2023-01-29 11-16-10](https://user-images.githubusercontent.com/3250792/215486995-d99c1af9-012a-4963-baec-4c846d656f95.png) But the game itself didn't launched, it failed to open graphics. It's probably due to the need to install xna31, but I couldn't install dotnet2 that is a prerequisite. That's probably an box86 issue there.
> 
> Euro Truck also installed without issue. The 64bits version launch and works, using dxvk ![Screenshot at 2023-01-29 20-28-03](https://user-images.githubusercontent.com/3250792/215487465-1a82c2e0-e0e8-4359-815f-caf5acff0976.png)
> 
> But the 32bits version doesn't, the dxvk context fails at creation.
> 
> I think the issue you have on your side is because PROOT doesn't handle Signal in a perfect way, and box86/box64 absolutly needs good signal handling, espcialy with program that use C# (or other languages using a JIT).

I think it's proot issue..
I tested without custom GPU driver same problem..
I tested with sysvipc same problem
I tested without sysvipc same problem
I tested with my custom GPU driver same problem..

Only Euro truck simulator 2 working inside fex-emulator.. but openrail exe opening.. but when i launch game fully crashed inside `fex-emulator` also....

## I think is proot issue but i believe if i create issues inside proot.. will ignore..

![IMG_20230127_041309](https://user-images.githubusercontent.com/72664192/215489032-7d133261-ec0f-4aea-b706-f85d9ff39da7.jpg)
![Screenshot_2023-01-27-04-12-39-476_com gaurav avnc](https://user-images.githubusercontent.com/72664192/215489115-aec893c2-b030-4c5d-aa72-45e01e948721.jpg)

**Comment by ThieuMinh26** [comment] 2023-01-30 13:46
> Signal mean? & Anyway to solve?

Well i think you will need arm soc with linux distro OR linux vm using Android KVM

**Comment by Saikatsaha1996** [comment] 2023-01-30 13:52
> > Signal mean? & Anyway to solve?
> 
> Well i think you will need arm soc with linux distro OR linux vm using Android KVM

I don't have Google tensor processor..
In mediatek processor i think not available KVM..
I am using fast time mediatek processor.. so i don't know much about mediatek processor..
