### ISSUE TITLE
Can Box86 run TrackMania server?

### ISSUE THREAD

**Issue by GreffMASTER** [ptitSeb/box86#137] opened 2020-06-26 13:20 UTC
I tried to run TrackMania Nations Forever server to see if it will actually work. I know that it's not in compatibility list, but i'm curious if it's possible.

Here's the launch log:
`./box86 /home/pi/TMUFServer/TrackmaniaServer /game_settings=MatchSettings/Nations/NationsBlue.txt /dedicated_cfg=dedicated_cfg.txt
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 26 Env var
Looking for /home/pi/TMUFServer/TrackmaniaServer
14291|0x8a42c20: Unimplemented Opcode 3E 74 02 FF D0 8B 45 D0
Aborted`

I completely accept the idea of impossibility to run this.

**Comment by ptitSeb** [comment] 2020-06-26 16:25
I have added the missing opcode, it should be farther now.

**Comment by GreffMASTER** [comment] 2020-06-26 17:03
Hey! It started now! Thanks a lot...

Now there's a new error.
`./box86 /home/pi/TMUFServer/TrackmaniaServer BOX86_LOG 3 /game_settings=MatchSettings/Nations/NationsBlue.txt /dedicated_cfg=dedicated_cfg.txt
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 26 Env var
Looking for /home/pi/TMUFServer/TrackmaniaServer
Starting TmForever v2011-02-21...
Error: Unsupported Syscall 0x10Fh (271)`

**Comment by ptitSeb** [comment] 2020-06-26 17:11
I added the missing syscall.

**Comment by GreffMASTER** [comment] 2020-06-26 17:35
Ok, more progress... now it's Unsupported Syscall 0x42h (66)
`Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 44 Env var
Looking for TrackmaniaServer
Starting TmForever v2011-02-21...
Initializing...
Configuration file : dedicated_cfg.txt
Loading system configuration...
...system configuration loaded
Loading cache...
...OK
Listening for xml-rpc commands on port 5000.
Trackmania server daemon started with pid=24137 (parent=24136).
Error: Unsupported Syscall 0x42h (66)`

**Comment by ptitSeb** [comment] 2020-06-26 17:39
Added that syscall too.

**Comment by GreffMASTER** [comment] 2020-06-26 18:01
Ok... so there's a little problem...
After the server launches it automatically detaches itself from the console (that's what it normally does) and it crashes afterwards, so I can't see the error.
And the log file only shows this:
`[2020/06/26 19:56:22] Initializing...
[2020/06/26 19:56:23] Configuration file : dedicated_cfg.txt
[2020/06/26 19:56:23] Loading system configuration...
[2020/06/26 19:56:23] ...system configuration loaded
[2020/06/26 19:56:23] Loading cache...
[2020/06/26 19:56:23] ...OK
[2020/06/26 19:56:23] Listening for xml-rpc commands on port 5000.
[2020/06/26 19:56:24] Loading dedicated server configuration...
[2020/06/26 19:56:24] ...Dedicated server configuration loaded
[2020/06/26 19:56:24] Match settings file : MatchSettings\Nations\NationsBlue.txt
[2020/06/26 19:56:24] Loading match settings...
[2020/06/26 19:56:24] ...Match settings loaded
[2020/06/26 19:56:24] Autostart server on internet
[2020/06/26 19:56:24] Connecting to master server...
[2020/06/26 19:56:24] ...ERROR: internal server error
[2020/06/26 19:56:25] Please wait, loading...`

An internal server error.

**Comment by ptitSeb** [comment] 2020-06-26 18:08
try to use `BOX86_TRACE_FILE=trace.txt` to send all box86 log in a file...

**Comment by GreffMASTER** [comment] 2020-06-26 18:31
The trace file doesn't seem to create. I tried with `BOX86_TRACE=1` and `BOX86_TRACE_INIT=1` but I can't find the file anywhere.

**Comment by GreffMASTER** [comment] 2020-06-26 18:43
I always used `strace` to trace the server output, but for that i need an PID. I don't have enough time to write the PID before the server crashes.

**Comment by ptitSeb** [comment] 2020-06-26 18:51
> The trace file doesn't seem to create. I tried with `BOX86_TRACE=1` and `BOX86_TRACE_INIT=1` but I can't find the file anywhere.

I think the trace is create in another place. Use a full path for trace (like `BOX86_TRACE_FILE=~/trace.txt) to be sure if it creation folder.

**Comment by GreffMASTER** [comment] 2020-06-26 19:04
Well... I tried that as well.
There's one more thing. I think, that server creates a completely new process using settings from the first one. So even if the trace file would create, it will trace only the first process (up too `Trackmania server daemon started with pid=28664 (parent=28656).`)

**Comment by ptitSeb** [comment] 2020-06-26 19:45
Ah, so a trace with pid in the name should be created? Mmmm, that could be possible I guess, but I have to think about it.

Isn"t there an option to avoid the pocess to demonize?

**Comment by GreffMASTER** [comment] 2020-06-26 19:50
No, I don't think there is.
I'm working on a shell script that can read the pid from the shell log and use it in strace. So it will attach the second the other process starts.

**Comment by GreffMASTER** [comment] 2020-06-26 20:48
OMG I DID IT! I almost gave up trying to make this script but at last... IT WORKS!
I got the error. Unsupported Syscall 0xC4h.

**Comment by ptitSeb** [comment] 2020-06-26 21:12
Ok, good :)

I have added the syscall.

**Comment by GreffMASTER** [comment] 2020-06-27 09:05
Ok. Later on, the server displays that the server is not running `[2020/06/27 10:48:52] Server not running, exiting.` After that i tries to relaunch the serve... but it fails. `write(1, "Starting TmForever v2011-02-21.."..., 228) = -1 EBADF (Bad file descriptor)
brk(0x3afb000)                          = 0x3afb000
munmap(0xb6f12000, 4096)                = 0
exit_group(1)                           = ?
+++ exited with 1 +++`

**Comment by GreffMASTER** [comment] 2020-06-27 09:20
Here's the full trace that I captured using strace.
[https://www.dropbox.com/s/fup7rngcd8uqyjz/TMtrace.txt?dl=0](url)

**Comment by ptitSeb** [comment] 2020-06-27 09:37
I suppose the strace is not running from the launch of the demon because I don't see how file descriptor 4, 5, 6 and 7 are created. The issue seems here I think, because they never have anything ready to read for the whole process, untill the server say it exit and the FD are closed.

**Comment by GreffMASTER** [comment] 2020-06-27 09:55
I managed to capture the full trace from start to bottom.
https://www.dropbox.com/s/4efbq7hxue61xzl/FullTrace.txt?dl=0

**Comment by ptitSeb** [comment] 2020-06-27 12:20
I don't see anything wrong. 
I have updated the elfloader a bit, can you retry, just in case it magically fixed this issue too?

If not, I think I'll have to debug on my side.

**Comment by GreffMASTER** [comment] 2020-06-27 12:44
Nope. Still the same error.

Anyway, I really appreciate your effort in this project. Keep the good work! : )

**Comment by ptitSeb** [comment] 2020-06-27 13:26
So I checked a bit on my side, and I see it's fully staticaly-linked binary: even libc is inside. This kind of binary is very difficult to emulate with box86 (that tries to wrap lib call into native calls). There is nothing towrap here, just system calls. But the problem is that the libc that use box86 can interfeare with the statically linked libc inside the server (especially pthread).

Not sure I can make this one works fine.

Anyway, I have a question: I downloaded the server and just launch the file. But it seems to complain about mssing configuration  and gameserver name... What is the minimal configuration step to be done to have it running? (I need to try on an x86 platform too to check default behavior).

**Comment by GreffMASTER** [comment] 2020-06-27 13:36
Yes, you need to set the parameters for the executable `/game_settings=MatchSettings/Nations/NationsBlue.txt /dedicated_cfg=dedicated_cfg.txt`. The match settings file is for the server gamemode settings (maps, time limit, gamemode, etc.). The dedicated_cfg.txt is the main server config file. This is where you set the server name, server desc. 
One more thing. In order to connect the dedicated server to the master server, you will need a dedicated server account.
Only players that bought TrackMania United Forever can create the dedicated server account. I can create and send you the account details (login, password) in a DM. You can read this forum post if you want to learn more.
http://www.tm-forum.com/viewtopic.php?t=14203

**Comment by ptitSeb** [comment] 2020-06-27 13:42
Ah ok.

Don't bother with the account for new. I'll check later if I need one (I gather one if I really need one)

**Comment by ptitSeb** [comment] 2022-10-11 14:33
TrackManiaServer is a 64bits now it seems. And it start with box64 but there is a missing opcode it seems (66 0F 3A 0C C4 01 blendps xmm0, xmm4, 0x01), which is SSE4.1

Closing this ticket (feel free to open a ticket in box64 repo for TrackManiaServer if needed)

**Closed by ptitSeb** 2022-10-11 14:33 UTC
