### ISSUE TITLE
[...]/steam: No such file or directory

### ISSUE THREAD

**Issue by Android-PowerUser** [ptitSeb/box86#802] opened 2023-03-30 00:02 UTC
/home/Win11/.local/share/Steam/steam.sh: line 788: /home/Win11/.local/share/Steam/ubuntu12_32/steam: No such file or directory.

But the 6 MB file is available. Suggested solutions, on a different thread, to the same problem didn't work for me.
(Termux PRoot Ubuntu)

**Comment by ptitSeb** [comment] 2023-03-30 06:11
You don't have binfmt integration, so you need to setup BO_BASH correctly and use `box64 steam` to launch steam.

**Comment by Android-PowerUser** [comment] 2023-03-30 10:54
I put BO_BASH=/bin/bash in $home/.bashrc.  But i have the same problem.

**Comment by ptitSeb** [comment] 2023-03-30 11:04
I made a Typo... Please read this: https://box86.org/2022/09/running-bash-with-box86-box64/

**Comment by Android-PowerUser** [comment] 2023-03-30 15:03
The error seems to be solved now, but no window is opened and I don't think any other serious error is displayed either.

Win11@localhost:/$ box64 steam
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096 lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
Running on Unknown CPU with 8 Cores
Params database has 22 entries
Using bash "/root/box64/tests/bash"
Box64 with Dynarec v0.2.3 900f3877 built on Mar 22 2023 07:33:12
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 51 Env var
Looking for steam
Apply RC params for steam
Applying BOX64_CRASHHANDLER=1
Applying BOX64_EMULATED_LIBS=libudev.so.0
Not an ELF file (sign=#!/u)
Error: reading elf header of /usr/lib/steam/bin_steam.sh, try to launch using bash instead
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096 lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
Running on Unknown CPU with 8 Cores
Params database has 22 entries
Using bash "/root/box64/tests/bash"
Box64 with Dynarec v0.2.3 900f3877 built on Mar 22 2023 07:33:12
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 51 Env var
Looking for /root/box64/tests/bash
bash detected, disabling banner
argv[1]="/usr/lib/steam/bin_steam.sh"
Rename process to "bash"
Using native(wrapped) libtinfo.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096 lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
Running on Unknown CPU with 8 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 900f3877 built on Mar 22 2023 07:33:12
BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/
BOX64_PATH: ./:bin/
Counted 53 Env var
Looking for /root/box64/tests/bash
bash detected, disabling banner
argv[1]="/root/.local/share/Steam/steam.sh"
Rename process to "bash"
Using native(wrapped) libtinfo.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
steam.sh[10656]: Running Steam on ubuntu 22.04 64-bit
steam.sh[10656]: STEAM_RUNTIME is enabled by the user
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096 lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
Running on Unknown CPU with 8 Cores
Params database has 22 entries
Box64 with Dynarec v0.2.3 900f3877 built on Mar 22 2023 07:33:12
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 60 Env var
Looking for /root/box64/tests/bash
bash detected, disabling banner
argv[1]="/root/.local/share/Steam/ubuntu12_32/steam-runtime/setup.sh"
Rename process to "bash"
Using native(wrapped) libtinfo.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
setup.sh[10986]: Steam runtime environment up-to-date!
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
steam.sh[10656]: Can't find 'steam-runtime-check-requirements', continuing anyway
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
Box86 with Dynarec v0.3.1 13bbf105 built on Mar 26 2023 01:22:22
src/tier0/threadtools.cpp (2377) : Assertion Failed: Function not implemented
src/tier0/threadtools.cpp (2377) : Assertion Failed: Function not implemented
/data/src/tier0/threadtools.cpp 2377 Assertion Failed: Function not implementedsrc/tier0/threadtools.cpp (1974) : Assertion Failed: semaphore creation failed Function not implemented
src/tier0/threadtools.cpp (1974) : Assertion Failed: semaphore creation failed Function not implemented
/data/src/tier0/threadtools.cpp 1974 Assertion Failed: semaphore creation failed Function not implementedsrc/tier0/threadtools.cpp (2377) : Assertion Failed: Function not implemented
src/tier0/threadtools.cpp (2377) : Assertion Failed: Function not implemented
/data/src/tier0/threadtools.cpp 2377 Assertion Failed: Function not implementedsrc/tier0/threadtools.cpp (1804) : Thread synchronization object is unuseable
src/tier0/threadtools.cpp (1804) : Thread synchronization object is unuseable
/data/src/tier0/threadtools.cpp 1804 Thread synchronization object is unuseable

**Comment by ptitSeb** [comment] 2023-03-30 15:17
This is now a duplicate of #699 . Closing this one.

**Closed by ptitSeb** 2023-03-30 15:17 UTC
